### ISSUE TITLE
helcim.com offline

### ISSUE THREAD

**Issue by jayvdb** [studybuffalo/django-helcim#120]
For about a day I have watched https://www.helcim.com and secure.myhelcim.com are offline.  I havent seen any news about the company/service falling over/shutting down, but then the news is a bit preoccupied atm.

**Comment by studybuffalo** [comment]
I am not actually affiliated with Helcim in any way, so I don't have much to add. I can say I haven't seen any communication of issues via email on my personal or professional emails though.

**Comment by jayvdb** [comment]
It is still down, so perhaps permanently broken.  A note on the README would be helpful.

**Comment by studybuffalo** [comment]
I am actually working on this app right now and am having no issues with helcim.com or the Helcim API (at least making test calls and using the account dashboard). Is it possible this is a local/limited issue?

**Comment by jayvdb** [comment]
Interesting ... when I use a web proxy , it is fine.

I tried three ISPs in Indonesia, http and https .. all timeout.

Possibly blocking/blocked in Indonesia.
